# site
name: Gustavo Tavares
email: ovatsug25@gmail.com
title: "Inspired by Dragon Fruit"
baseurl: ""
url: http://hylotron.com

defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "sidebar.html"
  -
    scope:
      path: "success_guide"
      type: "page"
    values:
      layout: "success_guide_index"
collections:
  success_guide:
    output: true
    layout: "success_guide_index"
    # label:
    # relative_directory:
    # directory:
    # output:
    # DOCUMENT
      # content:
      # output:
      # path:
      # relative_path:
      # url:

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
sass:
    sass_dir: _sass
include:     ['.htaccess']
exclude:
  - questions.txt
  - config.ru
  - Procfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - gems
keep_files:  ['.git','.svn']
# gems:        []
# timezone:    nil
encoding:    utf-8

future:      true
show_drafts: nil
limit_posts: 0
highlighter: pygments

relative_permalinks: true
permalink: /:categories/:title

permalink:     date
# paginate_path: 'page:num'
# paginate:      nil

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        3008
baseurl:     ""
url:         http://localhost:3001
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

twitter_url: http://twitter.com/ovatsug25/
