source: .
destination: ./_site
includes: ./_site

markdown: rdiscount
pygments: true

exclude: [ 'Rakefile', 'config.rb' ]

# exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
# permalink: /:categories/:year/:month/:day/:title
