# site
name: Gustavo Tavares
email: ovatsug25@gmail.com
title: "Inspired by Dragon Fruit"
baseurl: ""
url: http://hylotron.com

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
sass:
    sass_dir: _sass
include:     ['.htaccess']
exclude:
  - questions.txt
  - config.ru
  - Procfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - gems
keep_files:  ['.git','.svn']
# gems:        []
timezone:    nil
encoding:    nil

future:      true
show_drafts: nil
limit_posts: 0
highlighter: pygments

relative_permalinks: true
permalink: /:categories/:title

permalink:     date
paginate_path: 'page:num'
paginate:      nil

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        3008
baseurl:     ""
url:         http://localhost:3001
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

twitter_url: http://twitter.com/ovatsug25/



# Plugin: jekyll-assets
#
assets:
  # js_compressor: uglifier
  css_compressor: sass
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  dirname: assets
  # Base URL of assets paths.
  baseurl: /assets/
  # Pathnames where to find assets relative to the root of the site.
  sources:
  - _assets/javascripts
  - _assets/stylesheets
  - _assets/images
  # Sets JS compressor. No compression by default.
  # Possible variants: 'yui', 'uglifier', nil
  js_compressor: ~
  # Sets CSS compressor. No compression by default.
  # Possible variants: 'yui', 'sass', nil
  css_compressor: ~
  # Sets cachebusting policy for generated assets.
  # Possible variants:
  #   none - disables cachebusting
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css
  #   soft - leave filenames as-is, but `?cb=<md5>` suffix for URLs generated
  #          with `asset_path`, `javascript` and `stylesheet`:
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css?cb=4f41243847da693a4f356c0486114bc6
  #   hard - (default) injects cachebusting checksum into processed filename:
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app-4f41243847da693a4f356c0486114bc6.css
  #     output URL:   /assets/javascripts/app-4f41243847da693a4f356c0486114bc6.css
  cachebust: hard
  # Whenever or not cache compiled assets (disabled by default).
  # See `Compilation Cache` section of README for details.
  cache: false
  # Specifies list of MIME types that needs to have gzipped versions.
  # You can set it to `false` to disable gzipping. Only javascripts and
  # stylesheets are gzipped by default.
  gzip: [ text/css, application/javascript ]
  # Does not concatenates files requested by `javascript` and `stylesheet`
  # helpers. Instead outputs multiple files in order they are required.
  # Default: false
  debug: false
